- service: example.v1.ExampleService
  match:
  - name: somename
    headers:
      someheaderkey:
        exact: someheadervalue
    hosts:
    - address-one
    - address-two
    loadBalancer:
      type: pick_first
  - name: someothername
    headers:
      someheaderkey:
        exact: someotherheadervalue
    hosts:
    - address-three
    - address-four
    loadBalancer:
      type: random
  hosts:
  - default-adress
  loadBalancer:
    type: pick_first
