- name: somename
  service: example.v1.ExampleService
  methods:
  - name: ExampleMethod
    match:
    - name: somename
      headers:
        someheaderkey:
          exact: someheadervalue
      hosts:
      - address-one
      - address-two
      loadBalancer:
        type: peak_first
    match:
    - name: someothername
      headers:
        someheaderkey:
          exact: someotherheadervalue
      hosts:
      - address-three
      - address-four
      loadBalancer:
        type: peak_first
    hosts:
    - default-adress
    loadBalancer:
      type: peak_first